### ISSUE TITLE
Započítat výkaz práce jako pohotovost podle příznaku v "Dokumentace - z.p."

### ISSUE THREAD

**Issue by calaveraInfo** [cestadomu/cd-intuo-web-ui#5]
Ahoj Františku,

potřebovali bychom udělat změnu u výkazů práce:

Aktuálně se všechny Výkazy práce na dokumentaci zobrazují jako Nepohotovost. (Což bylo pravděpodobně původní zadání.) Nyní bychom chtěli změnit tak, aby se u Výkaz práce na dokumentaci započítával jako Pohotovost x Nepohotovost podle údaje Dokumentace - z.p. (WayOfWorking).

Díky

Šugy

**Comment by calaveraInfo** [comment]
Zjistil jsem, ze 1) vykaz prace na dokumentaci by v aktualni verzi uz mel prochazet uplne stejnou klasifikaci, jako standardni vykaz a 2) ta klasifikace je o dost slozitejsi (pripojuji pro ilustraci primo dotycny kus kodu). Je potreba to jeste jednou zkontrolovat.

switch(item.get('TypeClass')) {
        case 'Výkaz práce': //Výkaz práce 85953
        case 'Výkaz práce na dokumentaci': //Výkaz práce na dokumentaci 85954
            var poradi = item.get('start').getDate();
            var totalDuration = item.get('durationtime') + item.get('transportDuration');
            category = 'xxx';
            if (item.get('ServiceType') == 'Z - Čekání na práci v pohotovosti') {
                category = 'cekaniNaPraci';
            } else if (item.get('ServiceType') == 'Návštěva u lékaře') {
                category = 'lekar';
            } else if (item.get('ServiceType') == 'Neplacené volno') {
                category = 'lekar';
            } else if(item.get('wayOfWorking') == 'Pohotovost') {
                category = 'pohotovost';
            } else if (item.get('wayOfWorking') == 'Nepohotovost') {
                category = 'nepohotovost';
            } else {
                category = 'xxx';
            }
            dny[poradi][category] += totalDuration;
            break;

**Comment by psuchman** [comment]
Problém bude možná v tom, že číselník je jeden, ale pro výkaz na dokumnetaci se ukládá do tabulky cdServices pod documentationWayOfWorking, ale Výkaz práce je ve sloupci wayOfWorking - každý typ výkazu má pro stejný číselník jiný DB sloupec !?

**Comment by calaveraInfo** [comment]
To bude určitě ono, díky moc! Opravím to někdy o víkendu.
